<?php

namespace app\modules\marketing\models;

use Yii;

/**
 * This is the model class for table "contract_two".
 *
 * @property int $id
 * @property int $month_id
 * @property int $sum
 * @property string $current_date
 * @property int $contract_id
 *
 * @property Contract $contract
 * @property Months $months
 */
class ContractTwo extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'contract_two';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['month_id', 'sum', 'current_date', 'contract_id'], 'required'],
            [['month_id', 'sum', 'contract_id'], 'integer'],
            [['current_date'], 'string'],
            [['contract_id'], 'exist', 'skipOnError' => true, 'targetClass' => Contract::className(), 'targetAttribute' => ['contract_id' => 'id']],
            [['month_id'], 'exist', 'skipOnError' => true, 'targetClass' => Months::className(), 'targetAttribute' => ['month_id' => 'id']],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'month_id' => 'Month ID',
            'sum' => 'Sum',
            'current_date' => 'Current Date',
            'contract_id' => 'Contract ID',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getContract()
    {
        return $this->hasOne(Contract::className(), ['id' => 'contract_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getMonths()
    {
        return $this->hasOne(Months::className(), ['id' => 'month_id']);
    }
    public function beforeSave($insert)
    {
        $totals=Contract::findOne(['id'=>1]);
        if(Yii::$app->request->post()){
            $totals=$totals+$this->sum;
            return $totals;
        }
        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }
}
