<?php

namespace app\modules\teacher;
use app\models\User;
use yii\web\ForbiddenHttpException;

/**
 * teacher module definition class
 */
class TeacherModule extends \yii\base\Module
{
    public $layout='main';
    /**
     * @inheritdoc
     */
    public $controllerNamespace = 'app\modules\teacher\controllers';

    /**
     * @inheritdoc
     */
    public function init()
    {
        parent::init();

        // custom initialization code goes here
    }
    public function beforeAction($action)
    {
        if(!\Yii::$app->user->isGuest){
            if(\Yii::$app->user->identity->getRole() !== User::ROLE_TEACHER)
                throw new ForbiddenHttpException("Siz bu sahifaga kirish huquqiga ega emassiz");
        }
        else{
            throw new ForbiddenHttpException("Siz bu sahifaga kirish huquqiga ega emassiz");
        }
        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }
}
