<?php

namespace app\modules\subject;
use app\models\User;

/**
 * subject module definition class
 */
class SubjectModule extends \yii\base\Module
{
    public $layout = 'main';
    /**
     * @inheritdoc
     */

    public $controllerNamespace = 'app\modules\subject\controllers';

    public static $access_roles = [User::ROLE_ADMIN];
    /**
     * @inheritdoc
     */
    public function init()
    {
        parent::init();

        // custom initialization code goes here
    }

    public function beforeAction($action)
    {
        if(!\Yii::$app->user->isGuest){
            $role = \Yii::$app->user->identity->getRole();
            if(!in_array($role ,static::$access_roles))
                throw new ForbiddenHttpException("Siz bu sahifaga kirish huquqiga ega emassiz");
        }
        else{
            throw new ForbiddenHttpException("Siz bu sahifaga kirish huquqiga ega emassiz");
        }
        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }
}
