<?php

namespace app\modules\subject;
use app\models\User;

/**
 * subject module definition class
 */
class SubjectModule extends \yii\base\Module
{
    public $layout = 'main';
    /**
     * @inheritdoc
     */

    public $controllerNamespace = 'app\modules\subject\controllers';

    /**
     * @inheritdoc
     */
    public function init()
    {
        parent::init();

        // custom initialization code goes here
    }
    public function beforeAction($action)
    {
        if(!\Yii::$app->user->isGuest){
            if(\Yii::$app->user->identity->getRole() !== User::ROLE_SUBJECT)
                throw new ForbiddenHttpException("Siz bu sahifaga kirish huquqiga ega emassiz");
        }
        else{
            throw new ForbiddenHttpException("Siz bu sahifaga kirish huquqiga ega emassiz");
        }
        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }
}
