<?php

namespace app\modules\student;

use app\models\User;
use yii\web\ForbiddenHttpException;

/**
 * student module definition class
 */
class StudentModule extends \yii\base\Module
{
    /**
     * @inheritdoc
     */
    public $controllerNamespace = 'app\modules\student\controllers';

    public $layout ='main';
        /**
         * @inheritdoc
         */
    public function init()
    {
        parent::init();

        // custom initialization code goes here
    }
    public function beforeAction($action)
    {
        if(\Yii::$app->user->isGuest){
            if(\Yii::$app->user->identity->getRole() !== User::ROLE_STUDENT)
                throw new ForbiddenHttpException("Siz bu sahifaga kirish huquqiga ega emassiz");
        }
        else{
            throw new ForbiddenHttpException("Siz bu sahifaga kirish huquqiga ega emassiz");
        }
        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }
}
