<?php

namespace app\modules\marketing;
use app\models\User;
use yii\web\ForbiddenHttpException;

/**
 * modules module definition class
 */
class Module extends \yii\base\Module
{
    /**
     * @inheritdoc
     */
    public $controllerNamespace = 'app\modules\marketing\controllers';

    public $layout='main';
    /**
     * @inheritdoc
     */


    public static $access_roles = [User::ROLE_CONTRACT,User::ROLE_ADMIN];
    /**
     * @inheritdoc
     */
    public function init()
    {
        parent::init();

        // custom initialization code goes here
    }

    public function beforeAction($action)
    {
        if(!\Yii::$app->user->isGuest){
            $role = \Yii::$app->user->identity->getRole();
            if(!in_array($role ,static::$access_roles))
                throw new ForbiddenHttpException("Siz bu sahifaga kirish huquqiga ega emassiz");
        }
        else{
            throw new ForbiddenHttpException("Siz bu sahifaga kirish huquqiga ega emassiz");
        }
        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }
}
